name: Powershell

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install PSScriptAnalyzer module
      run:
        Install-Module -Name 'PSScriptAnalyzer' -Force
    - name: Run Invoke-ScriptAnalyzer
      run:
        if (Invoke-ScriptAnalyzer -Path .) {Write-Error "Invoke-ScriptAnalyzer is reporting some issues"}
    - name: Publish to PSGallery Repo
      env:
        NUGETAPIKEY: ${{ secrets.EventLogTools }} 
      run:
        write-host "current path is $pwd.Path"
        if (test-path -path 'c:\program files\windowspowershell\modules') {write-host 'path exists'}
        else {write-host 'path doesn't exist}
        Publish-Module -Name 'EventLogTools' -NuGetApiKey $env:NUGETAPIKEY
