name: Powershell

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install PSScriptAnalyzer module
      run:
        Install-Module -Name 'PSScriptAnalyzer' -Force
    - name: Run Invoke-ScriptAnalyzer
      run:
        if (Invoke-ScriptAnalyzer -Path .) {Write-Error "Invoke-ScriptAnalyzer is reporting some issues"}
    - name: Copy to Modules Folder
      run: 
        $ModuleFolder = 'c:\program files\windowspowershell\modules\EventLogTools'
        New-Item -ItemType 'Directory' -Path $ModuleFolder
        Get-ChildItem -Path . -Recurse | Copy-Item -Destination $ModuleFolder
    - name: Publish to PSGallery Repo
      env:
        NUGETAPIKEY: ${{ secrets.EventLogTools }} 
      run:
        Import-Module -Name EventLogTools
        #Publish-Module -Name 'EventLogTools' -NuGetApiKey $env:NUGETAPIKEY
