name: Powershell

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install PSScriptAnalyzer module
      run:
        Install-Module -Name 'PSScriptAnalyzer' -Force
    - name: Run Invoke-ScriptAnalyzer
      run:
        if (Invoke-ScriptAnalyzer -Path .) {Write-Error "Invoke-ScriptAnalyzer is reporting some issues"}
    - name: Publish to PSGallery Repo
      env:
        NUGETAPIKEY: ${{ secrets.EventLogToolsApiKey }} 
      run:
        if ($NUGETAPIKEY) {write-host 'there is something inside nugetkey var'}
        else {write-host 'nope nothing'}
        #Publish-Module -Name 'EventLogTools' -NuGetApiKey $nugetkey
