name: Powershell

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check if Nuget is installed
      run:
        Get-PackageProvider
        
